// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.SuberSirAntsABot2.autonomousroutines;

import org.usfirst.frc3244.SuperSirAntsABot2.Constants;
import org.usfirst.frc3244.SuperSirAntsABot2.Robot;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.ConditionalCommand;


/**
 *
 */
public class Auto_30_0_Deliver_No_Cube_BaseLine_or_Cross extends ConditionalCommand {

    public Auto_30_0_Deliver_No_Cube_BaseLine_or_Cross() {
      super(new Auto_30_1_Cross_Field_to_Left_Scale_From_Right(), new Auto_00_Reach_BaseLine());
    }

    @Override
    protected boolean condition(){
    	Integer crossFieldChoice = (Integer) Robot.crossFieldChooser.getSelected();
    	DriverStation.reportError("RUNING: Auto_30_0_Deliver_No_Cube_BaseLine_or_Cross()", false);
    	
    	if(crossFieldChoice != null) {
    		if(crossFieldChoice == 0){
    			DriverStation.reportError("No Cross", false);
    			return false;
    		}else{
    			DriverStation.reportError("Cross Field to Prep", false);
    			return true;
    		}
        }else {
        	DriverStation.reportError("crossFieldChoice Null", false);
        	return false;
        }
    }
}
